controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController


effort_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      # Leg 1
      - hip_joint_1
      - knee_joint_1
      - ankle_joint_1
      # Leg 2
      - hip_joint_2
      - knee_joint_2
      - ankle_joint_2
      # Leg 3
      - hip_joint_3
      - knee_joint_3
      - ankle_joint_3
      # Leg 4
      - hip_joint_4
      - knee_joint_4
      - ankle_joint_4
      # Leg 5
      - hip_joint_5
      - knee_joint_5
      - ankle_joint_5
      # Leg 6
      - hip_joint_6
      - knee_joint_6
      - ankle_joint_6